### ISSUE TITLE
Create ERD for user services

### ISSUE THREAD

**Issue by jacky-htg** [opensource-edukasi/user-services#2]
Create ERD for user services

**Comment by jacky-htg** [comment]
https://drive.google.com/file/d/1DYYwsCgV0HFRJw4rPADC09kN6SQz-S4N/view?usp=sharing

**Comment by jacky-htg** [comment]
DONE

**Comment by hustleroleplayid** [comment]
ijin minta akses mas: fbhantu781@gmail.com
